### PR TITLE
Merge forked Telemachus with canonical Telemachus

### PR DESCRIPTION
**Pull request by tcannonfodder**
## Add Mechjeb staging simulation and maneuver node endpoints

In [Houston](http://github.com/tcannonfodder/houston), BOOST uses the staging info for a burn planner and FIDO can create/edit/update maneuver nodes. 

The staging info endpoint is: `mj.stagingInfo`. The endpoint returns a JSON object with 2 keys: `atmo`
and `vacuum`. These objects are arrays with the raw data from the
staging simulation. It returns `null` if Mechjeb is not found or the module is not turned on.

The endpoint for the orbit's maneuver nodes is `o.maneuverNodes`, which returns an array of the orbit's
maneuver nodes. This information includes the time of UT of the maneuver
node, the deltaV of the maneuver node, and the orbit details for the
maneuver node. There are also the endpoints:

* `o.addManeuverNode`
* `o.updateManeuverNode`
* `o.removeManeuverNode`

LMK if you have any questions! :smile:

### CODE REVIEW

**Comment by cashelcomputers** [comment]
Wow! I was looking for this functionality (esp setting and getting maneuver nodes), awesome stuff! Off to hack my code to include stuff that can use this, thanks heaps!

**Comment by tcannonfodder** [comment]
Of course, happy it's helping! I packaged it all up into a release here: https://github.com/tcannonfodder/Telemachus/releases/tag/v1.4.32.0

**Comment by tcannonfodder** [comment]
Oh, if you want to see some of these endpoints in action, Houston is in 0.5 prerelease right now :) https://github.com/tcannonfodder/houston/releases/tag/0.5-beta

**Comment by cashelcomputers** [comment]
Nice, went to check it out but it ain't working, have submitted a issue. Cheers

**Pull request merged**
